version: '3.8'

services:
  web:
    build: .
    ports:
      - "8010:8010"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"