version: "3.8"

services:
  web:
    build: .
    ports:
      - "8010:8010"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - postgres_password=password
      - postgres_db=mydb
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always

  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
